[HEADER(is_skippable=false, is_tutorial=true)] 挑战模式
[Tutorial(waitForSignal="sandbox_v2_home_entry_routed", dialogHead="$avatar_zumama")]
[Tutorial(target="btn_sandbox_v2_challenge_mode_entry", animStyle="Highlight",            focusStyle="HighlightRect", black="$f_tut_black", protectTime=0.8, dialogHead="$avatar_zumama")] 「危道」試験演算ができるようになったようだ。
[Tutorial(target="btn_sandbox_v2_challenge_mode_entry", animStyle="Highlight",            focusStyle="HighlightRect", black="$f_tut_black", protectTime=0.8, dialogHead="$avatar_zumama")] この演算では、環境が絶えず悪化していく――と聞くと恐ろしげだろうが、これはゼロから始めなくてもいいんだ。通常の演算データから、直近の決算日を読み込んで、それを基に新たな演算を開始できるぞ。
[Tutorial(protectTime=0.8, dialogHead="$avatar_zumama")] 「危道」試験演算では、セーブやロードを使うことはできないし、ストーリーを進めることもできない。
[Tutorial(protectTime=0.8, dialogHead="$avatar_zumama")] また、演算中に失敗、あるいは自主的に終了すると、データは「危道」試験演算の開始前の状態に戻るようになっているぞ。この演算で加えた変更は、いずれもデータとして保存されないので留意してくれ。